// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsa0mfqjDpHy-qncQ0vZ1WetQIzur-hnE',
    appId: '1:572066362861:web:ff823b4c48f9b05babe3e4',
    messagingSenderId: '572066362861',
    projectId: 'unikit-b3681',
    authDomain: 'unikit-b3681.firebaseapp.com',
    storageBucket: 'unikit-b3681.appspot.com',
    measurementId: 'G-DECEEHN5G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6H37H-hymt48Hz5EcG-kgO2Fe1DBM5gs',
    appId: '1:572066362861:android:6c3b9d4f35db7c85abe3e4',
    messagingSenderId: '572066362861',
    projectId: 'unikit-b3681',
    storageBucket: 'unikit-b3681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCED3nrbtyGuvERkc9C6soAPhoGoGczrbY',
    appId: '1:572066362861:ios:1d452c46adf2cd32abe3e4',
    messagingSenderId: '572066362861',
    projectId: 'unikit-b3681',
    storageBucket: 'unikit-b3681.appspot.com',
    iosBundleId: 'com.example.unikit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCED3nrbtyGuvERkc9C6soAPhoGoGczrbY',
    appId: '1:572066362861:ios:1d452c46adf2cd32abe3e4',
    messagingSenderId: '572066362861',
    projectId: 'unikit-b3681',
    storageBucket: 'unikit-b3681.appspot.com',
    iosBundleId: 'com.example.unikit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsa0mfqjDpHy-qncQ0vZ1WetQIzur-hnE',
    appId: '1:572066362861:web:073d6d711a2da6f1abe3e4',
    messagingSenderId: '572066362861',
    projectId: 'unikit-b3681',
    authDomain: 'unikit-b3681.firebaseapp.com',
    storageBucket: 'unikit-b3681.appspot.com',
    measurementId: 'G-DKYDVBDV9N',
  );

}